repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      # XXX: disable for tanapaste
      # - id: trailing-whitespace
      # - id: end-of-file-fixer  # files end always in newline

      - id: check-merge-conflict
      # Syntax checks
      - id: check-ast  # valid Python parse
      - id: check-yaml
      - id: check-toml

      # TODO: this one should NOT fix within dotfiles e.g. OrcaSlicer
      # - id: check-json

      # TODO: maybe:
      # https://github.com/pre-commit/pre-commit-hooks?tab=readme-ov-file#name-tests-test
      # --pytest-test-first
      # - check-shebang-scripts-are-executable

  # Ruff = linter + import sorter + formatter
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.10
    hooks:
      - id: ruff-check
        args: [--fix]
      - id: ruff-format

  # Static type checking
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        additional_dependencies:
          # deps of gatelet that still lack bundled typings
          - types-python-dateutil  # indirect via httpx / fastapi
          - homeassistant-stubs
          - types-Markdown
          - types-toml
          - types-tabulate

  # Buildifier for Bazel files
  - repo: https://github.com/keith/pre-commit-buildifier
    rev: 6.4.0
    hooks:
      - id: buildifier
      - id: buildifier-lint
