"""HTTP status codes and other constants."""

# HTTP Status codes
SC_OK = 200
SC_CREATED = 201
SC_REGISTER_SENSOR = 301
SC_INVALID_JSON = 400
SC_UNAUTHORIZED = 401
SC_MOBILE_COMPONENT_NOT_LOADED = 404
SC_INTEGRATION_DELETED = 410

# Port numbers
DEFAULT_NOTIFIER_PORT = 8400
OAUTH_CALLBACK_PORT = 9736
